version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5431:5432
    environment:
      POSTGRES_PASSWORD: admin

  api:
    build: .
    ports:
      - 3000:3000
    restart: on-failure
    environment:
      - PORT=3000
      - DATABASE_URL=tododb
    depends_on:
      - db