version: '3.8'

services:
  #  todoDb:
  #    image: postgres
  #    restart: always
  #    ports:
  #      - 5433:5432
  #    environment:
  #      POSTGRES_PASSWORD: admin

  todo_api:
    build:
      context: .
      args:
        - DATABASE_HOST=db
        - DATABASE_PORT=5432
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=admin
        - DATABASE_NAME=todo
        - AUTH_SERVICE_URL=http://auth_api:8080
        - SERVER_PORT=3000
    ports:
      - 3000:3000
    restart: on-failure
    #    depends_on:
    #      - todoDb
    networks:
      - authservice_default
networks:
  authservice_default:
    external: true