apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-db
spec:
  serviceName: todo-db
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
        - name: todo-db
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: admin
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: todo-db
spec:
  selector:
    app: todo-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      containers:
        - name: api
          image: akselsaatci/todoservice-api:latest
          env:
            - name: DB_HOST
              value: todo-db
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: admin
            - name: DB_NAME
              value: todo
            - name: PORT
              value: "3000"

          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app: todo-service
  type: NodePort
  ports:
    - name: http
      port: 31648
      targetPort: 3000