version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin

  auth_api:
    build:
      context: .
      args:
        - DATABASE_HOST=db
        - DATABASE_PORT=5432
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=admin
        - DATABASE_NAME=auth
        - SERVER_PORT=8080
        - JWT_SECRET_KEY=qwe
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - db